---
# Sets working environment on Debian to sensible state

- name: Install Czech locale
  locale_gen:
    name: "{{ item }}"
    state: present
  with_items:
    - "en_US.UTF-8"
    - "cs_CZ.UTF-8"

- name: Set timezone
  timezone:
    name: Europe/Prague

- name: Install vim, htop, locate
  apt:
    name:
      - vim
      - htop
      - locate

- name: create /root/.bashrc if it does not exist
  copy:
    content: ""
    dest: /root/.bashrc
    force: no

- name: fix cmd prompt
  blockinfile:
    dest: /root/.bashrc
    block: |
      # If this is an xterm set the title to user@host:dir
      case "$TERM" in
      xterm*|rxvt*)
         PS1="\[\e]0;\u@$HOSTNAME \w\a\]\u@$HOSTNAME:\w# "
         ;;
      *)
         ;;
      esac
      export EDITOR=vi

- name: "set /etc/vim/vimrc.local"
  copy:
    dest: /etc/vim/vimrc.local
    content: |
      " fix mouse
      set mouse=r
      " syntax highlighting
      syntax on
      set background=dark
      " jump to the last position when reopening a file
      au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

- name: "disable defaults.vim to be loaded"
  lineinfile:
    path: /etc/vim/vimrc
    regexp: 'let g:skip_defaults_vim = 1'
    line: 'let g:skip_defaults_vim = 1'

- name: dir /root/.config/htop exists
  file:
    path: /root/.config/htop
    state: directory

- name: create /root/.config/htop/htoprc
  copy:
    content: ""
    dest: /root/.config/htop/htoprc
    force: no

- name: htop hide user threads
  lineinfile:
    path: /root/.config/htop/htoprc
    regexp: '^hide_userland_threads='
    line:   'hide_userland_threads=1'
